import type { AppleVisualAsset } from './asset-image-model'

export const visualAssets: AppleVisualAsset[] = [
  {
    id: 'iphone-default',
    kind: 'hardware',
    category: 'iPhone',
    matchKeywords: ['IPHONE'],
    thumbnail: '/apple-assets/hardware/iphone.svg',
    image: '/apple-assets/hardware/iphone.svg',
    source: 'local-placeholder',
  },
  {
    id: 'ipad-default',
    kind: 'hardware',
    category: 'iPad',
    matchKeywords: ['IPAD'],
    thumbnail: '/apple-assets/hardware/ipad.svg',
    image: '/apple-assets/hardware/ipad.svg',
    source: 'local-placeholder',
  },
  {
    id: 'mac-default',
    kind: 'hardware',
    category: 'Mac',
    matchKeywords: ['MAC', 'MACBOOK', 'MBA', 'MBP'],
    thumbnail: '/apple-assets/hardware/mac.svg',
    image: '/apple-assets/hardware/mac.svg',
    source: 'local-placeholder',
  },
  {
    id: 'watch-default',
    kind: 'hardware',
    category: 'Apple Watch',
    matchKeywords: ['WATCH'],
    thumbnail: '/apple-assets/hardware/watch.svg',
    image: '/apple-assets/hardware/watch.svg',
    source: 'local-placeholder',
  },
  {
    id: 'airpods-default',
    kind: 'hardware',
    category: 'AirPods',
    matchKeywords: ['AIRPODS'],
    thumbnail: '/apple-assets/hardware/airpods.svg',
    image: '/apple-assets/hardware/airpods.svg',
    source: 'local-placeholder',
  },
  {
    id: 'app-default',
    kind: 'software',
    category: 'App',
    matchKeywords: ['APP'],
    thumbnail: '/apple-assets/software/app.svg',
    image: '/apple-assets/software/app.svg',
    source: 'local-placeholder',
  },
  {
    id: 'subscription-default',
    kind: 'software',
    category: 'Subscription',
    matchKeywords: ['SUBSCRIPTION', 'ICLOUD', 'APPLE MUSIC'],
    thumbnail: '/apple-assets/software/subscription.svg',
    image: '/apple-assets/software/subscription.svg',
    source: 'local-placeholder',
  },
  {
    id: 'store-credit-default',
    kind: 'software',
    category: 'Store Credit',
    matchKeywords: ['STORE CREDIT', 'GIFT'],
    thumbnail: '/apple-assets/software/store-credit.svg',
    image: '/apple-assets/software/store-credit.svg',
    source: 'local-placeholder',
  },
  {
    id: 'placeholder-default',
    kind: 'placeholder',
    matchKeywords: [],
    thumbnail: '/apple-assets/placeholders/default.svg',
    image: '/apple-assets/placeholders/default.svg',
    source: 'local-placeholder',
  },
]
